### ISSUE TITLE
Problem with installing via maven

### ISSUE THREAD

**Issue by damomeen** [BandwidthOnDemand/nsi-dds-client#1]
Hi,

I would like to test your client for NSI but have problem with installation:

root@debian:~/nsi-dds-client# mvn clean install -e
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building nsi-dds-client 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for org.dstovall:onejar-maven-plugin:jar:1.4.4 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.492s
[INFO] Finished at: Fri Aug 05 04:42:30 CDT 2016
[INFO] Final Memory: 5M/15M
[INFO] ------------------------------------------------------------------------
[ERROR] Plugin org.dstovall:onejar-maven-plugin:1.4.4 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.dstovall:onejar-maven-plugin:jar:1.4.4: Failure to find org.dstovall:onejar-maven-plugin:pom:1.4.4 in http://onejar-maven-plugin.googlecode.com/svn/mavenrepo was cached in the local repository, resolution will not be reattempted until the update interval of onejar-maven-plugin.googlecode.com has elapsed or updates are forced -> [Help 1]
org.apache.maven.plugin.PluginResolutionException: Plugin org.dstovall:onejar-maven-plugin:1.4.4 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.dstovall:onejar-maven-plugin:jar:1.4.4
        at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolve(DefaultPluginDependenciesResolver.java:129)
        at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getPluginDescriptor(DefaultMavenPluginManager.java:142)
        at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getMojoDescriptor(DefaultMavenPluginManager.java:261)
        at org.apache.maven.plugin.DefaultBuildPluginManager.getMojoDescriptor(DefaultBuildPluginManager.java:185)
        at org.apache.maven.lifecycle.internal.DefaultLifecycleExecutionPlanCalculator.calculateLifecycleMappings(DefaultLifecycleExecutionPlanCalculator.java:280)
        at org.apache.maven.lifecycle.internal.DefaultLifecycleExecutionPlanCalculator.calculateMojoExecutions(DefaultLifecycleExecutionPlanCalculator.java:193)
        at org.apache.maven.lifecycle.internal.DefaultLifecycleExecutionPlanCalculator.calculateExecutionPlan(DefaultLifecycleExecutionPlanCalculator.java:112)
        at org.apache.maven.lifecycle.internal.DefaultLifecycleExecutionPlanCalculator.calculateExecutionPlan(DefaultLifecycleExecutionPlanCalculator.java:129)
        at org.apache.maven.lifecycle.internal.BuilderCommon.resolveBuildPlan(BuilderCommon.java:92)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: org.sonatype.aether.resolution.ArtifactDescriptorException: Failed to read artifact descriptor for org.dstovall:onejar-maven-plugin:jar:1.4.4
        at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:296)
        at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(DefaultArtifactDescriptorReader.java:186)
        at org.sonatype.aether.impl.internal.DefaultRepositorySystem.readArtifactDescriptor(DefaultRepositorySystem.java:279)
        at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolve(DefaultPluginDependenciesResolver.java:115)
        ... 25 more
Caused by: org.sonatype.aether.resolution.ArtifactResolutionException: Failure to find org.dstovall:onejar-maven-plugin:pom:1.4.4 in http://onejar-maven-plugin.googlecode.com/svn/mavenrepo was cached in the local repository, resolution will not be reattempted until the update interval of onejar-maven-plugin.googlecode.com has elapsed or updates are forced
        at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:538)
        at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:216)
        at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:193)
        at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:281)
        ... 28 more
Caused by: org.sonatype.aether.transfer.ArtifactNotFoundException: Failure to find org.dstovall:onejar-maven-plugin:pom:1.4.4 in http://onejar-maven-plugin.googlecode.com/svn/mavenrepo was cached in the local repository, resolution will not be reattempted until the update interval of onejar-maven-plugin.googlecode.com has elapsed or updates are forced
        at org.sonatype.aether.impl.internal.DefaultUpdateCheckManager.newException(DefaultUpdateCheckManager.java:230)
        at org.sonatype.aether.impl.internal.DefaultUpdateCheckManager.checkArtifact(DefaultUpdateCheckManager.java:204)
        at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:427)
        ... 31 more
[ERROR]
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException

I'm not Java/maven developer and google search wasn't helping me to solve this issue.

root@debian:~/nsi-dds-client# java -version
java version "1.8.0_71"
Java(TM) SE Runtime Environment (build 1.8.0_71-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.71-b15, mixed mode)

root@debian:~/nsi-dds-client# lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 7.8 (wheezy)
Release:        7.8

Could you help?
Codename:       wheezy
root@debian:~/nsi-dds-client# j

**Comment by jmacauley** [comment]
The one-jar plug-in had been hosted on google but has since been moved
to the public maven.  This was causing the build failure.  Update dd151d3 corrected the one-jar location and the build once again is functioning correctly.

```

nsi-dds-client hacksaw$ mvn clean install
[INFO] Scanning for projects...
[INFO]
.
.
.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.712 s
[INFO] Finished at: 2016-08-05T09:14:14-04:00
[INFO] Final Memory: 23M/363M
[INFO] ------------------------------------------------------------------------
nsi-dds-client hacksaw$ 
nsi-dds-client hacksaw$ ./shell.sh 
Welcome to the DDS command shell.  Enter ?list for available commands.
dds> ls
/subscriptions (3)
/local (1)
/documents (58)
dds> cd documents
https://nsi-aggr-west.es.net/discovery/documents
dds/documents> ls
urn:ogf:network:surfnet.nl:1990:nsa:bod7 (3)
urn:ogf:network:kddilabs.jp:2013:nsa (2)
urn:ogf:network:ampath.net:2013:nsa (2)
urn:ogf:network:caltech.edu:2013:nsa (2)
urn:ogf:network:netherlight.net:2013:nsa:safnari (1)
urn:ogf:network:twaren.nchc.org:2014:nsa (2)
urn:ogf:network:sinet.ac.jp:2013:nsa (2)
urn:ogf:network:czechlight.cesnet.cz:2013:nsa (2)
urn:ogf:network:es.net:2013:nsa:nsi-aggr-west (1)
urn:ogf:network:geant.net:2013:nsa (7)
urn:ogf:network:icair.org:2013:nsa (2)
urn:ogf:network:manlan.internet2.edu:2013:nsa (2)
urn:ogf:network:netherlight.net:2013:nsa:bod (2)
urn:ogf:network:krlight.net:2013:nsa (2)
urn:ogf:network:jgn-x.jp:2013:nsa (2)
urn:ogf:network:aist.go.jp:2013:nsa (2)
urn:ogf:network:wix.internet2.edu:2013:nsa (2)
urn:ogf:network:aist.go.jp:2013:nsa:nsi-aggr (1)
urn:ogf:network:southernlight.net.br:2013:nsa (2)
urn:ogf:network:cipo.rnp.br:2014:nsa:safnari (1)
urn:ogf:network:uvalight.net:2013:nsa (2)
urn:ogf:network:es.net:2013:nsa (2)
urn:ogf:network:oess.dcn.umnet.umich.edu:2013:nsa (2)
urn:ogf:network:cipo.rnp.br:2014:nsa (2)
urn:ogf:network:surfnet.nl:1990:nsa:bod-acc (3)
urn:ogf:network:icair.org:2013:nsa:nsi-am-sl (1)
urn:ogf:network:openflow.netherlight.net:2016:nsa (2)
urn:ogf:network:nordu.net:2013:nsa (2)
dds/documents> cd urn:ogf:network:es.net:2013:nsa 
https://nsi-aggr-west.es.net/discovery/documents/urn:ogf:network:es.net:2013:nsa
dds/documents/urn:ogf:network:es.net:2013:nsa> ls
vnd.ogf.nsi.nsa.v1+xml (1)
vnd.ogf.nsi.topology.v2+xml (1)
dds/documents/urn:ogf:network:es.net:2013:nsa> cd vnd.ogf.nsi.nsa.v1+xml
https://nsi-aggr-west.es.net/discovery/documents/urn:ogf:network:es.net:2013:nsa/vnd.ogf.nsi.nsa.v1+xml
dds/documents/urn:ogf:network:es.net:2013:nsa/vnd.ogf.nsi.nsa.v1+xml> details
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns2:documents xmlns:ns6="http://nordu.net/namespaces/2013/12/gnsbod" xmlns:ns5="http://schemas.ogf.org/nsi/2013/09/topology#" xmlns:ns8="http://schemas.ogf.org/nsi/2014/02/discovery/nsa" xmlns:ns7="http://schemas.es.net/nsi/2014/03/pce/discovery/configuration" xmlns:ns9="http://schemas.ogf.org/nsi/2013/12/services/definition" xmlns:ns2="http://schemas.ogf.org/nsi/2014/02/discovery/types" xmlns:ns4="http://schemas.ogf.org/nml/2013/05/base#" xmlns:ns3="urn:ietf:params:xml:ns:vcard-4.0">
    <ns2:document id="urn:ogf:network:es.net:2013:nsa" href="https://nsi-aggr-west.es.net/discovery/documents/urn%3Aogf%3Anetwork%3Aes.net%3A2013%3Ansa/vnd.ogf.nsi.nsa.v1%2Bxml/urn%3Aogf%3Anetwork%3Aes.net%3A2013%3Ansa" version="2016-08-05T10:15:06.258Z" expires="2016-10-04T10:15:06.259Z">
        <nsa>urn:ogf:network:es.net:2013:nsa</nsa>
        <type>vnd.ogf.nsi.nsa.v1+xml</type>
        <content contentType="application/x-gzip" contentTransferEncoding="base64">H4sIAAAAAAAAAH1U0W6bMBT9FeTXCWwgSRNk6Lpqm/qyTUu2SX1zjUOsgo1sQ9u/38WQhCVaH6JcfM8518f32vT2tamDXhgrtcpRHBEUCMV1KVWVo1+7L+Ea3RZU2TRTlgUAVhaiNEcH59oMY8sPomE20tU+0qbCykqckHiBSYJLabkG7TdYZehETnLUGZVJ4fZZywxrbAYpSGQ9Z6YMF34Tr600wuYIxFZhTEKy2MUki5cZWUXJcvOIAlmOQlA6U8K9aPOcCRtBmAHJbxidrXkdsg7Jcq6zfkTgjjWi+LwFYvB9e3/3cxt0P+4o9svU6r17YUb8HoUKMPhkZFmJsI8pvsxS65hxOwnM/xUE0glDWdlIda+VY9wNx5yMZzCGnTwGRhaD0w5WMr7m5dPTmoQl4zdhHIs03PCYQSlCEkL4hq1WsPmJNkVHpdZAa6fYiVc32Q6Pxr9tH4JP3t5I9JgxnFON6CcNcAF2mnawuyDLON3Fm2WySB8n/ik/fp+Iz1LNtwFfspdlx+qrumfkXs0Y9wepgq+dfr4iHGHTn4WTGzp5xh5XfLqSvVBebUyO32M8KcCAy3pWmgP44zhpV8UnLJ61Ev/b5Fpz5vys1FpV0nWlKMI4SWA4SJJSfF6lNQB9lN5E65vVJoHscWkAHoWm6X8oi/fuA2zqhKNSOWH2jIOQe2tFwdq2lqMe7lXp7zOMesRt1CcR9B66I8wHq1lLsWfQgxH7YngGLLwD2oJZG431MJhVgg9iW2F6yWGaPJriWd29YK4zIhjUcnRd1OhaRHATEb7EwkNzgeW6aaS/U7pzqEgJoXjiFLQVcDv/SHcIBskcgeS7BwUPB/xkyKrKhC8wvxSfJHxrPaT4C3hlbLw8BQAA</content>
    </ns2:document>
</ns2:documents>

dds/documents/urn:ogf:network:es.net:2013:nsa/vnd.ogf.nsi.nsa.v1+xml> exit
/discovery/documents/urn:ogf:network:es.net:2013:nsa
dds/documents/urn:ogf:network:es.net:2013:nsa> exit
/discovery/documents
dds/documents> exit
/discovery
dds> exit
Exiting...

```
